// Define the package for this class
package com.luv2Code.cruddemo.entity;

// Import necessary JPA annotations for mapping
import jakarta.persistence.*;

/**
 * The Student class is a JPA entity that maps to the "student" table in the database.
 * It represents a student record with fields such as ID, first name, last name, and email.
 */
@Entity // Marks this class as a JPA entity to be managed by the JPA provider
@Table(name = "student") // Specifies the table name in the database
public class Student {

    // Define fields

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Specifies that the ID value will be generated by the database (auto-increment)
    @Column(name = "id") // Maps this field to the "id" column in the database
    private int id;

    @Column(name = "first_name") // Maps this field to the "first_name" column in the database
    private String firstName;

    @Column(name = "last_name") // Maps this field to the "last_name" column in the database
    private String lastName;

    @Column(name = "email") // Maps this field to the "email" column in the database
    private String email;

    // Define constructors

    /**
     * Default constructor for JPA.
     * It is required by the JPA specification for entity instantiation.
     */
    public Student() {
        // No-arg constructor
    }

    /**
     * Parameterized constructor to create a new Student instance.
     *
     * @param firstName The first name of the student.
     * @param lastName The last name of the student.
     * @param email The email of the student.
     */
    public Student(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    // Define setters/getters

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    // Define toString() method

    /**
     * Generates a string representation of the Student object.
     *
     * @return A string with the student's ID, first name, last name, and email.
     */
    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
